name: Ecommerce Build and Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted 
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure Docker
      run: |
        # This uses the 'gcloud' helper directly which is the most reliable way on a locked VM
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Build and Push Docker Image
      run: |
        # We add 'sudo' here just in case the runner doesn't have permission to talk to the Docker socket
        sudo docker build -t us-central1-docker.pkg.dev/internal-sandbox-446612/ecommerce-repo/app:${{ github.sha }} .
        sudo gcloud docker -- push us-central1-docker.pkg.dev/internal-sandbox-446612/ecommerce-repo/app:${{ github.sha }}

    - name: Get GKE Credentials
      run: |
        # Connecting to your cluster without needing a separate secret key
        gcloud container clusters get-credentials my-gke-cluster --zone asia-south1-a

    - name: Deploy to GKE
      run: |
        # Creates YOUR unique store separate from TravelX
        kubectl create deployment maglin-store --image=us-central1-docker.pkg.dev/internal-sandbox-446612/ecommerce-repo/app:${{ github.sha }} --dry-run=client -o yaml | kubectl apply -f -
        
        # Exposes it on a brand new IP address
        kubectl expose deployment maglin-store --type=LoadBalancer --port=80 --target-port=8080 --dry-run=client -o yaml | kubectl apply -f -
        
        # Forces the app to update if it's already there
        kubectl set image deployment/maglin-store app=us-central1-docker.pkg.dev/internal-sandbox-446612/ecommerce-repo/app:${{ github.sha }}
        
        kubectl rollout status deployment/maglin-store
