name: Ecommerce Build and Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted 
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure Docker
      run: |
        # This bypasses the 'Read Only' scope by using your active session token
        echo $(gcloud auth print-access-token) | docker login -u oauth2access-token --password-stdin https://us-central1-docker.pkg.dev

    - name: Build and Push Docker Image
      run: |
        docker build -t us-central1-docker.pkg.dev/internal-sandbox-446612/ecommerce-repo/app:${{ github.sha }} .
        docker push us-central1-docker.pkg.dev/internal-sandbox-446612/ecommerce-repo/app:${{ github.sha }}

    - name: Get GKE Credentials
      run: |
        # Connecting to your cluster without needing a separate secret key
        gcloud container clusters get-credentials my-gke-cluster --zone asia-south1-a

    - name: Deploy to GKE
      run: |
        # Creates YOUR unique store separate from TravelX
        kubectl create deployment maglin-store --image=us-central1-docker.pkg.dev/internal-sandbox-446612/ecommerce-repo/app:${{ github.sha }} --dry-run=client -o yaml | kubectl apply -f -
        
        # Exposes it on a brand new IP address
        kubectl expose deployment maglin-store --type=LoadBalancer --port=80 --target-port=8080 --dry-run=client -o yaml | kubectl apply -f -
        
        # Forces the app to update if it's already there
        kubectl set image deployment/maglin-store app=us-central1-docker.pkg.dev/internal-sandbox-446612/ecommerce-repo/app:${{ github.sha }}
        
        kubectl rollout status deployment/maglin-store
